[formatter.alejandra]
command = "alejandra"
options = ["--quiet"]
includes = ["*.nix"]

[formatter.shfmt]
command = "shfmt"
options = [
  "-i",
  "2",
  "-s",
  "-w",
]
includes = [".sh", ".bash"]

[global]
excludes = [
  ".age",
  ".key",
  ".git/",
  ".direnv/",
  "result",
  "result-*",
  ".vscode/",
  ".idea/",
  "node_modules/**",
]
